<?php

/**
 * BFL CatalogProduct
 *
 * @category   BFL CatalogProduct Module
 * @package    BFL CatalogProduct
 * @copyright  2019 All rights reserved.
 * @license    Proprietary
 * @author     BFL (bajaj finserv limited)
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="a_bestSellSec">
        <div class="container">
            <div class="a_sellingInner">
                <?php if ($block->getTitle()): ?>
                    <div class="block-title">
                        <h2><?= $block->escapeHtml(__($block->getTitle())) ?></h2>
                    </div>
                <?php endif ?>
                <div class="a_row8">
                    <div class="a_slidingPart">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                            <div class="a_boxPad">
                                <div class="a_mainBoxshad">
                                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                        <div class="a_imgPart">
                                            <?= $block->getImage($_item, $image)->toHtml() ?>
                                        </div>
                                        <div class="a_selCon">
                                            <p class="a_proName"><?= $block->escapeHtml($_item->getName()) ?></p>
                                            <p class="a_emiAt">EMI starting at</p>
                                            <p class="a_emiMo"><?= $block->getProductPrice($_item) ?><sub>/month</sub></p>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>