<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>
<?php if ($block->getWishlistHelper()->isAllow()): ?>
<?php
    /** @var \Magento\Wishlist\Helper\Data $wishlistHelper */
    $wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
    $wishlistItem = $wishlistHelper->getWishlistItemCollection()->getItemByColumnValue('product_id', $block->getProduct()->getId());
    $isAddedInWishilistURL = $block->getAddToWishlistParams($block->getProduct());
    $isAddedInWishilist = 'fa fa-heart-o';
?>
    <?php if($wishlistItem): ?>
        <?php $isAddedInWishilist = "fa fa-heart"; ?>
        <?php $isAddedInWishilistURL = $wishlistHelper->getRemoveParams($wishlistItem); ?>
    <?php endif; ?>
    <div class="a_wishPro" data-id ='<?= $block->getProduct()->getId();?>' data-href='<?= /* @noEscape */ $isAddedInWishilistURL ?>'><i class="<?= $isAddedInWishilist ?>"></i></div>
    <input type="hidden" value="<?= $block->getProduct()->getId() ?>">
<?php endif; ?>

