<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_reviewHelper = $this->helper('Cybage\Productdetail\Helper\Data');
$_expertReviewData=array();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="mobFiler">
        <ul>
            <li>
                <a href="javascript:void(0);" class="a_opnFilter"><img src="<?= $this->getViewFileUrl('images/filterBlue.svg'); ?>" alt=""> Filter</a>
            </li>
            <li>
                <a href="javascript:void(0);" class="a_opnSort"><img src="<?= $this->getViewFileUrl('images/sortBlue.svg'); ?>" alt=""> Sort</a>
            </li>
        </ul>
    </div>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item-detailed-info">
                <div class="product-item-info-details" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <div class="product-info-image">
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                            <?php $noCostEmi = $_product->getResource()->getAttribute('no_cost_emi')->getFrontend()->getValue($_product); ?>
                            <?php $zeroDownpayment = $_product->getResource()->getAttribute('zero_downpayment')->getFrontend()->getValue($_product); ?>
                            <div class="product-item-no-cost-payment">
                                <?php if($noCostEmi): ?>
                                        <div class="no-cost-emi"><label><?= /* @escapeNotVerified */ __('No Cost EMI') ?></label></div>
                                <?php endif; ?>
                                <?php if($zeroDownpayment) : ?>
                                     <div class="zeropayment">                                         
                                     <label><?= /* @escapeNotVerified */ __(' 0% Down Payment') ?></label></div> 
                                <?php endif; ?>
                            </div>
                            <div class="product-item-spece-core">
                                <?php $specScore = $_product->getResource()->getAttribute('spec_score')->getFrontend()->getValue($_product); ?> 
                                <?php $specOverClass='';?>
                                <?php if($specScore>50): ?>
                                    <?php $specOverClass="over50";?>
                                <?php endif;?>
                                <?php $specScoreClass= 'p'.round($specScore)?>
                                <div class="progress-circle <?= $specOverClass; ?><?= $specScoreClass; ?>">
                                    <p><?= /* @escapeNotVerified */ __(round($specScore).'%') ?></p>
                                    <div class="left-half-clipper">
                                        <div class="first50-bar"></div>
                                        <div class="value-bar"></div>
                                    </div>
                                </div>
                                <p><?= /* @escapeNotVerified */ __(' Spec Score') ?></p>
                            </div>  
                            
                        </a>
                    </div>
                    <div class="product details product-item-details">
                       
                        <?php $_expertReviewData = $_reviewHelper->getRatingSummary($_product);?>
                    <div class="product-reviews-summary short">
                        <?php if(isset($_expertReviewData['rating_percent']) && ($_expertReviewData['rating_percent'] !=='')):?>
                        
                            <div class="rating-summary">
                                <span class="label"><span><?=  /* @escapeNotVerified */ __('Rating:') ?></span></span>
                                <div class="rating-result" title="<?= /* @escapeNotVerified */
                 $_expertReviewData['rating_percent']; ?>%">
                                    <span style="width:<?= /* @escapeNotVerified */
                     $_expertReviewData['rating_percent']; ?>%"><span><?= /* @escapeNotVerified */
                             $_expertReviewData['rating_percent']; ?>%</span></span>
                                </div>
                            </div>
                            <div class="reviews-actions">
                                <a class="action view" href="#">&nbsp;<span><?= /* @escapeNotVerified */
                     $_expertReviewData['reviews_count']; ?></span></a>
                            </div>
                            <?php endif;?>
                        </div>
                        
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                         
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner-details">
                             <div class="emiPart">
                                <?php $emi = $_product->getResource()->getAttribute('emi_starting_at')->getFrontend()->getValue($_product); ?>
                                <h4><?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($emi, true, false); ?><?= /* @escapeNotVerified */ __('/month') ?></h4>
                            </div>
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                         
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<div class="wishlistTips"></div>
<script>
require(['jquery', 'jquery/jquery-storageapi'], function($) {
    $.cookieStorage.set('mage-messages', '');
    $(document).ready(function () {
        if ($(window).width() < 768) {            
            if ($('.filter-content').length > 0) {
                var getfilterHeight = $(window).height();
                var getheght = getfilterHeight - 66;
                $('.filter-content').height(getheght);
            }
        }
        $('[data-role=ln_content]').find('li:nth-child(7)').nextAll().addClass('d-none');
        $(document).on('click', '.seeMore', function () {
            var id = $(this).attr('id');            
            $(this).siblings('.items').children('li.d-none').removeClass('d-none');           
            $(this).addClass('d-none');
        });  
    });
});
</script>
