version: 0.0
os: linux

files:
  - source: ./app
    destination: /app/magento/emimall-uat/app
  - source: ./customcron
    destination: /app/magento/emimall-uat/customcron

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root

  ApplicationStart:
    - location: scripts/changepermission.sh
      timeout: 3600 


  ValidateService:
    - location: scripts/status_service.sh
      timeout: 3600
      runas: root
