<?php
/**
 * BFL Cybage_CustomWishlist
 *
 * @category   Cybage_CustomWishlist
 * @package    BFL Cybage_CustomWishlist
 * @copyright  2019 All rights reserved.
 * @license    Proprietary
 * @author     BFL (bajaj finserv limited)
 */
// @codingStandardsIgnoreFile
?>
<div class="p_wishlisthold">
    <!-- Logic to get Sold Qty dynamically yet to implement-->
    <p>4,500 Sold</p>
</div>