<?php
/*  Copyright (c) BFL (bajaj finserv limited), India  */
// @codingStandardsIgnoreFile
    
$slUrl = $block->getUrl('storelocator/index/index');
$sessionUrl = $block->getUrl('storelocator/index/session');
$isLoggedIn = $this->helper('Cybage\CustomWishlist\Helper\Data')->isCustomerLoggedIn();
?>
<script>
    require(['jquery','mage/url'],function($,url) {
        $(document).ready(function(){
            var isLoggedIn = 1;
            var slUrl = '<?php echo $slUrl; ?>';
            var sessionUrl = '<?php echo $sessionUrl; ?>';
            isLoggedIn = <?php echo $isLoggedIn ? $isLoggedIn : 0; ?>;
            $("body").on("click", ".p_wishlistgetpro", function(){
                var prodId = $(this).attr('id');
                console.log("prodId = "+prodId);
                var categoryLob = $(this).find(".categorylob").val();
                console.log("CategoryLob = "+categoryLob);
                if (isLoggedIn) {
                    if(typeof categoryLob !== 'undefined' && categoryLob !== ""){
                        $.ajax({
                            url: sessionUrl,
                            type: 'POST',
                            data: {categorylob: categoryLob},
                            dataType: 'json',
                            success: function () {
                                window.location.href = slUrl;
                            }
                        });
                    }
                } else {
                    $('.a_pstpLonMainblack').addClass('a_pstpLonMainblackshow');
                    $('.a_pstpLonMain').addClass('a_pstpLonMainShow');
                }
            });
        });
    });
</script>