<?php
/**
 * BFL Cybage_CustomWishlist
 *
 * @category   Cybage_CustomWishlist
 * @package    BFL Cybage_CustomWishlist
 * @copyright  2019 All rights reserved.
 * @license    Proprietary
 * @author     BFL (bajaj finserv limited)
 */
// @codingStandardsIgnoreFile

$item = $block->getItem();
$product = $item->getProduct();
$attributeSetId = $product->getAttributeSetId();
$categoryLob = $this->helper('Cybage\Storelocator\Helper\Category')->getCategoryLob($attributeSetId);
?>
<div class="p_wishlistEMi">
    <p>EMI starting at</p>
    <h2><?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($product->getData('emi_starting_at'), true, false); ?></h2>
</div>
<div class="p_wishlistgetpro" id="item_<?php echo $item->getId();?>">
    <a href="javascript:void(0)">Get this product</a>
    <input class="categorylob"type="text" value="<?php echo $categoryLob;?>" hidden="true"/>
</div>

