<?php

$specifictions = $block->getProductSpecification();
$descriptor = $this->helper('Cybage\Attributemapping\Helper\Data')->getAttributes($block->getProduct()->getSku());
if (!empty($descriptor['short_descriptor'])) {
    $description = $descriptor['short_descriptor'];
} else {
    $description = '';
}
?>

<div class="prodDesPdp" id="productDes3">
        <?php if (!empty(trim($description))) {?>
    <div class="p_productdescription">
        <div class="p_titlepro">
            <strong><?= /* @noEscape */ __('Product Description');?></strong>
        </div>
        <p><?= /* @noEscape */ $description ?>
        </p>
        <a href="javascript:void(0);"><?= /* @noEscape */ __('More'); ?></a>
    </div>
        <?php } ?>
    <?php if (isset($specifictions)) {?>
    <div class="p_productspeci">
        <div class="p_productone">
            <a href="javascrit:void(0);"><strong>Product Specifications</strong> <i class="fa fa-minus"></i></a>
            <div class="p_genreltabel p_genreltabelShow">

                <?php foreach ($specifictions as $groupname => $attributelist) : ?>
                <div class="p_genralteb">
                    <div class="p_titleteb">
                        <strong><?= /* @noEscape */ $groupname ?></strong>
                    </div>
                    <ul>
                        <?php foreach ($attributelist as $attributelabel => $attributeValue) : ?>
                        <li>
                            <p class="p_greeytext"><?= /* @noEscape */ $attributelabel ?></p>
                            <p class="p_blcktext"><?= /* @noEscape */ $attributeValue ?></p>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <?php } ?>
</div>