<?php 
$footer = $this->helper('Cybage\Attributemapping\Helper\Data')->getAttributes($block->getProduct()->getSku());
if(is_array($footer)) :
?>
<div class="a_colapsFoot">
    <p>
        <?php
        if (isset($footer['footer_title'])) {
            echo $footer['footer_title'];
        }
        ?>
    </p>
<i class="fas fa-angle-down"></i></div>
<div class="a_footerWhite">
    <div class="container">
        <div class="a_fBallIn">
            <div class="a_footerBlock">
                    <?php
                    if (isset($footer['footer_content'])) {
                        echo $footer['footer_content'];
                    }
                    ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>