<?php
/*  Copyright (c) BFL (bajaj finserv limited), India  */
// @codingStandardsIgnoreFile
?>
<div class="fullpageBar">
    <ul>
        <li><a href="#overview1" class="active"><?= /* @escapeNotVerified */ __('Overview') ?></a></li>
        <li><a href="#keyspaces2" class=""><?= /* @escapeNotVerified */ __('Key Specs') ?></a></li>
        <li><a href="#productDes3" class=""><?= /* @escapeNotVerified */ __('Product Description') ?></a></li>
        <li><a href="#experRew4" class=""><?= /* @escapeNotVerified */ __('Expert Reviews') ?></a></li>
        <li><a href="#faqsPdp" class=""><?= /* @escapeNotVerified */ __('FAQs') ?></a></li>
    </ul>
</div>