<?php
$specscore = $block->getProductSpecScore();
$keySpecs = $block->getSpecGroup();
$inCompareList = $this->helper('Cybage\CatalogProduct\Helper\Product\Compare\Data')->isInCollection($block->getProduct());
if($inCompareList){
    $params = $this->helper('Magento\Catalog\Helper\Product\Compare')->getPostDataRemove($block->getProduct());
}else {
    $params = $this->helper('Magento\Catalog\Helper\Product\Compare')->getPostDataParams($block->getProduct());
}
?>

<div class="p_shareandcompere">
    <div class="p_btnrows">
        <div class="p_sharesbtn">
            <a href="javascript:void(0);" class="shareMob">
                <img src="<?= /* @noEscape */ $block->getViewFileUrl('images/pdp/share-2.svg');?>" alt="share-2"> Share</a>
        </div>
        <div class="p_sharesbtn">
            <a href="#" data-post='<?= /* @noEscape */ $params ?>'
                data-role="add-to-links"
                class="action tocompare"><img src="<?= /* @noEscape */ $block->getViewFileUrl('images/pdp/compere.svg');?>" alt="compare"> Compare
            </a>
        </div>
    </div>
</div>

<?php if (!empty($keySpecs)) {?>
<div class="keuSpacePdp" id="keyspaces2">
    <div class="p_keyspeces">
        <div class="p_titlekeyspec">
            <strong><?= /* @noEscape */ __('Key Specs');?></strong>

            <div class="TOPspascore">
                <div class="progress-circle over50 p<?= /* @noEscape */ $specscore; ?>">
                    <p><?= /* @noEscape */ $specscore; ?>%</p>
                    <div class="left-half-clipper">
                        <div class="first50-bar"></div>
                        <div class="value-bar"></div>
                    </div>
                </div>
                <p><?= /* @noEscape */ __('Spec Score') ?></p>
            </div>
        </div>
        <div class="p_prefrencepartsrow">
            <?php foreach ($keySpecs as $keySpec => $value) {?>
                <div class="p_designprefrence">
                <div class="p_prefrencetitle">
                    <strong><?= /* @noEscape */ $keySpec?></strong>
                    <div class="ratedline">
                        <?php
                        if ($value <= 4) {
                            $class = "colred";
                        } elseif ($value > 4 && $value <= 6) {
                            $class = "colyellow";
                        } elseif ($value > 6 && $value <= 8) {
                            $class = "colgrean1";
                        } else {
                            $class = "colgrean2";
                        }
                        for ($i=1; $i<=10; $i+=2) {
                            if ($i > $value) {
                                $class = '';
                            }
                            ?>
                            <div class="<?= /* @noEscape */ $class ?>"></div>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <?php }?>
        </div>
        
    </div>
</div>
<?php } ?>
