<div class="P_specialprice">
    <ul>
        <li><img src="<?= /* @noEscape */ $block->getViewFileUrl('images/pdp/percentage-icon.svg'); ?>" alt="percentage-icon"/>
            <p>Special Price Extra <i class="fa fa-rupee"></i> 2000 discount (price inclusive of discount)</p>
        </li>
        <li><img src="<?= /* @noEscape */ $block->getViewFileUrl('images/pdp/percentage-icon.svg'); ?>" alt="percentage-icon"/>
            <p>Vijay Sales Offer 5% Cashback on RBL Bajaj Finserv Credit Card </p>
        </li>
    </ul>
</div>