<?php
/*  Copyright (c) BFL (bajaj finserv limited), India  */
// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Customer\Wishlist $block */

$wishlistItemsCollection = $this->helper('Magento\Wishlist\Helper\Data')->getWishlistItemCollection();
$wishlistItemsCount = $wishlistItemsCollection->getSize();
$url = $block->getUrl('customwishlist/index/ajaxload');
$slUrl = $block->getUrl('storelocator/index/index');
$sessionUrl = $block->getUrl('storelocator/index/session');
$wishlistHelper = $this->helper('Cybage\CustomWishlist\Helper\Data');
$httpRequest = $wishlistHelper->getHttpInstance();
$customerSession = $wishlistHelper->getCustomerSession();
$isLoggedIn = $customerSession->isLoggedIn();
$wishlistHelper->setReferrerUrl($httpRequest->getServer('HTTP_REFERER'));
$referrerUrl = $customerSession->getWishlistReferrerUrl();
?>
<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
    <?= ($block->getChildHtml('wishlist.rss.link')) ?>
    <form class="form-wishlist-items container" id="wishlist-view-form"
          data-mage-init='{"wishlist":{
          "addToCartUrl":<?= /* @noEscape */ $block->getItemAddToCartParams("%item%") ?>,
          "addAllToCartUrl":<?= /* @noEscape */ $block->getAddAllToCartParams() ?>,
          "commentString":""},
          "validation": {}}' action="<?= $block->escapeUrl($block->getUrl('wishlist/index/update', ['wishlist_id' => $block->getWishlistInstance()->getId()])) ?>" method="post">
              <?= $block->getChildHtml('top') ?>
        <div class="p_wishlistheader">
            <div class="p_wishlistbackpage">
                <a href="javascript:void(0)" id="wishlistBack"><img src="<?php echo $this->getViewFileUrl('images/back.svg'); ?>" alt=""></a>
                <h2>My Wishlist (<?php echo $wishlistItemsCount ?>)</h2>
            </div>
            <div class="p_wishclearall">
                <?php if($wishlistItemsCount > 0) : ?>
                    <a href="#" data-role="remove" data-post-remove='<?=/* @noEscape */ $this->helper('Cybage\CustomWishlist\Helper\Data')->getClearAllParams(); ?>'>Clear All</a>
                <?php endif; ?>
            </div>
        </div>
        <div class="p_wishlisttitle">
            <h2 class="p_pointwishlist">My Wishlist (<?php echo $wishlistItemsCount ?>)</h2>
            <a href="#" data-role="remove" data-post-remove='<?=/* @noEscape */ $this->helper('Cybage\CustomWishlist\Helper\Data')->getClearAllParams(); ?>' class="p_clearall">Clear All</a>
        </div>
        <?php if ($block->hasWishlistItems()): ?>
            <?= $block->getBlockHtml('formkey') ?>
            <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
            <?= $block->getChildHtml('items') ?>
        <?php else: ?>
            <div class="message info empty"><span><?= $block->escapeHtml(__('You have no items in your wish list.')) ?></span></div>
        <?php endif ?>
        <?= $block->getChildHtml('bottom') ?>
        <div class="actions-toolbar">
            <div class="primary">
                <?= $block->getChildHtml('control_buttons') ?>
            </div>
            <div class="secondary">
                <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back">
                    <span><?= $block->escapeHtml(__('Back')) ?></span>
                </a>
            </div>
        </div>    
    </form>
    <script id="form-tmpl" type="text/x-magento-template">
        <form id="wishlist-hidden-form" method="post" action="<%- data.url %>" class="no-display">
        <% if (data.qty) { %>
        <input name="qty" value="<%- data.qty %>">
        <% } %>

        <% if (data.item) { %>
        <input name="item" value="<%- data.item %>">
        <% } %>

        <% if (data.entity) { %>
        <input name="entity" value="<%- data.entity %>">
        <% } %>
        </form>
    </script>
    <?php if($wishlistItemsCount > 10) :?>
        <div id="load-more-wishlist-products" class="ias-trigger ias-trigger-next loadMoreBtn" style="text-align: center; cursor: pointer; font-size: 10px;" id="ias_trigger_1565597802825">
            <a style="text-transform:uppercase" href="javascript:void(0);">Load more</a>
        </div>
    <?php endif; ?>
    <?php endif ?>
    <input id="referrerUrl" type="text" value="" hidden="true"/>
<script>
require(['jquery','mage/url'],function($,url) {
    $(document).ready(function () {
        $('#load-more-wishlist-products').on('click', function () {
            var linkUrl = '<?php echo $url?>';
            $.ajax({
                url: linkUrl,
                type: 'get',
                dataType: 'html',
                showLoader: true,
                success: function(data) {
                    $(data).find('li').appendTo('ol');
                    $('#load-more-wishlist-products').hide();
                }
            });
        });
        
        /*Wishlist Back Url*/
        var refUrl = '<?php echo isset($referrerUrl)? $referrerUrl : 0?>';
        $('#wishlistBack').on('click', function(){
            if(typeof refUrl !== 'undefined' && refUrl !== "" && refUrl !== '0'){
                window.location.replace(refUrl);
            }else{
                window.location.replace(window.location.origin);
            }
        });
    });
});
</script>