<?php
$total = $block->getItems()->getSize();
$maxCounr = $block->getMaxCount();
$maxItems = $maxCounr['desktop'];
$maxMobileItem = $maxCounr['devices'];
$similarProducts = $block->getSimilarCategoryProducts();
$isLoggedIn = false;
if ($this->helper('Cybage\Storelocator\Helper\Category')->isCustomerLoggedIn()) {
    $isLoggedIn = true;
}
?>
<?php if ($total) : ?>
    <section class="p_selectproduct table">
        <div class="p_compierheader">
            <div class="p_compieartext">
             <a href="javascript:void(0);" id="compare_back"><img src="<?= $this->getViewFileUrl('images/arrow-left.png'); ?>" alt=""><h2>Compare</h2></a>   
             </div> 
             <div class="p_addproducticon">
                 <a href="javascript:void(0);"><img src="<?= $this->getViewFileUrl('images/plusicon.png'); ?>" alt=""></a>
             </div>
        </div>
        <div class="p_allselect_pro">
            <div class="p_comperproduct">
                <h2><?= $block->escapeHtml(__($block->getCompareProductsTitle())) ?></h2>
                <p><?= $total; ?> items</p>
                <div class="p_hidecommon">
                    <p>
                        <input type="checkbox" id="com1" value="Compare">
                        <label for="com1">Hide Common Features</label>
                    </p>
                </div>
            </div>

            <div class="p_selectanother_product">
                <div class="p_selectbox">
                    <div class="ipnovs">
                        <p><?= $block->escapeHtml(__($block->getCompareProductsTitle())) ?></p>
                        <p>V/S</p>
                        <p>Other</p>
                    </div>
                    <!--poboFixed-->
                    <?php
                    $intItems = 0;
                    $compareHelper = $this->helper('Cybage\CatalogProduct\Helper\Product\Compare\Data');
                    $helper = $this->helper('Magento\Catalog\Helper\Output');
                    $itemCollection = $block->getItems();
                    foreach ($itemCollection as $item) {
                        $intItems++;
                        
                        ?>
                        <div class="p_designbox" id="<?= $item->getCatalogCompareItemId()?>">
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : 
                                $wlparam = $block->getWishlistParams($item);
                                ?>
                                <div class="p_wishlist a_wishPro" data-href='<?= /* @escapeNotVerified */ $wlparam['data'] ?>' data-id = "<?= $item->getProductId(); ?>" data-action="add-to-wishlist">
                                    <i class="<?= $wlparam['class'];?>"></i>
                                </div>
                            <?php endif; ?>
                            <div class="p_closebtnicon">
                                <a href="#" data-post='<?= $compareHelper->getPostDataRemove($item) ?>'><i class="fa fa-times"></i></a>
                            </div>
                            <div class="p_comnocostdetils">
                                <div class="p_specescore">
                                <img src="<?= $this->getViewFileUrl('images/spccore.png'); ?>" alt="">
                                <p><?= round($item->getSpecScore())?><sub>%</sub></p>
                                </div>
                            </div>
                            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($item) ?>">
                                <div class="p_selectimg">
                                    <?= $block->getImage($item, 'product_comparison_list')->toHtml() ?>
                                </div>
                                <div class="p_detilselect">
                                    <h2><?= /* @escapeNotVerified */ $helper->productAttribute($item, $item->getName(), 'name') ?></h2>
                                    
                                </div>
                                <div class="p_emistarting">
                                    <p>EMI starting at</p>
                                    <h2><?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($item->getEmiStartingAt(), true, false); ?><sub>/month</sub></h2>
                                </div>
                            </a>
                            <div class="p_nearbystoreBuy">
                                <a href="javascript:void(0);"><?= __('Buy now'); ?></a>
                            </div>
                            <?php
                                $attributeSetId = $item->getAttributeSetId();
                                $categoryLob = $this->helper('Cybage\Storelocator\Helper\Category')->getCategoryLob($attributeSetId);
                            ?>
                            <div class="p_nearbystore" data-category-lob="<?php echo $categoryLob;?>">
                                <a href="javascript:void(0);"><?= __('Find store'); ?></a>
                            </div>
                        </div>
                        <?php
                    }
                    $count = 0;
                    if ($intItems < $maxItems) {
                        for ($j = $intItems + 1; $j <= $maxItems; $j++) {
                            $count++;
                            ?>
                            <div class="p_designbox_select displaynone">
                                <div class="p_seclectanother">
                                    <h2>Select another product</h2>
                                </div>
                                

                            <div class="p_productdrop ui-widget">
                                <input name="selectpro" class="p_serchproduct" id="p_serchproduct<?= $j;?>" placeholder="Search product">
                                <div class="p_listaddproduct"></div>
                            </div>
                            <div class="p_addproductbtn">
                                <?php //$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                    <a href="javascript:void(0)"title="<?= $block->escapeHtmlAttr(__('Add product')) ?>" 
                                        <?php  if ($count == 1) {
                                            ?>class="addPro" <?php
                                        } ?>>
                                        <?= $block->escapeHtmlAttr(__('Add Product')) ?>
                                    </a>
                            </div>
                            </div>
                            <?php
                        }?>
                        
                    <?php }
                    ?>
                </div>
            </div>
        </div>
        <div class="p_disproduct">
            <table style="width:100%" name="compare_description">
                <tr>
                    <th class="p_checkboxdesign" colspan="5">
                        <div class="p_hidecommon">
                            <p>
                                <input type="checkbox" id="com2" value="Compare">
                                <label for="com2">Hide Common Features</label>
                            </p>
                        </div>
                    </th>
                </tr>
                <tr>
                    <th class="p_productspe" colspan="5">
                        <span class="feature">
                            <span class="featurename">Product Specifications</span>
                        </span>
                    </th>
                </tr>

                <?php
                
                foreach ($block->getAttributes() as $attributeGroup => $attributeData) :
                    $attributeGroupRowStyle = $block->attributeGroupStyles[$attributeGroup];
                    ?>
                    <tr>
                        <th class="p_protitle <?= $attributeGroupRowStyle ?>" colspan="5"><p><?= $attributeGroup ?></p></th>
                    </tr>
                    <?php foreach ($attributeData as $code => $attribute) : ?>
                        <?php
                        $index = 0;
                        $attributeCodeRowStyle = $block->attributeCodeStyles[$code];
                        ?>
                        <tr class=<?= $attributeCodeRowStyle; ?>>
                            <?php
                                foreach ($block->getItems() as $item) : ?>
                                <?php if ($index++ == 0) : ?>
                                    <td class="p_spimobile">
                                        <p>
                                            <?= $block->escapeHtml($attribute->getStoreLabel() ? $attribute->getStoreLabel() : __($attribute->getFrontendLabel())) ?>
                                        </p>
                                    </td>
                                <?php endif; ?>
                                <td class="p_companey">
                                    <h2>
                                        <?php
                                        switch ($attribute->getAttributeCode()) {
                                            case "price":
                                                ?>
                                                <?php
                                                /* @escapeNotVerified */ echo $block->getProductPrice(
                                                    $item,
                                                    '-compare-list-' . $attribute->getCode()
                                                )
                                                ?>
                                                <?php
                                                break;
                                            case "small_image":
                                                ?>
                                                <?php $block->getImage($item, 'product_small_image')->toHtml(); ?>
                                                <?php
                                                break;
                                            default:
                                                ?>
                                                <?php if (is_string($block->getProductAttributeValue($item, $attribute))) : ?>
                                                    <?= /* @escapeNotVerified */ $helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode()) ?>
                                                    <?php
                                                else :
                                                    ?>
                                                    <?=
                                                    /* @escapeNotVerified */ $block->getProductAttributeValue($item, $attribute);
                                                endif;
                                                ?>
                                                <?php
                                                break;
                                        }
                                        ?>
                                    </h2>
                                    <p>
                                            <?= $block->escapeHtml($attribute->getStoreLabel() ? $attribute->getStoreLabel() : __($attribute->getFrontendLabel())) ?>
                                    </p>
                                </td>
                            <?php endforeach; ?>
                            <?php
                            $count = count($block->getItems());
                            while ($maxItems - $count > 0) {
                                echo '<td>-</td>';
                                $count++;
                            }
                            ?>
                        </tr>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </table>
        </div>
<div class="p_companerproduct_popup">
        <div class="p_compaerproductheader">
            <a href="javascript:void(0);"><img src="<?= $this->getViewFileUrl('images/closesim.png'); ?>" alt=""></a>
            <h2>Select Product to Compare</h2>
        </div>
        <div class="p_selectcompaer">
            <?php
            $mobilecount = 0;
            foreach ($itemCollection as $item) {
                $mobilecount++;
                ?>
            <div class="p_productnameimg">
                <div class="p_compaerproimg active">
                     <?= $block->getImage($item, 'product_comparison_list')->toHtml() ?>
                </div>
                <div class="p_compierselectinput">
                    
                    <div class="p_productdrop ui-widget">
                        <a href="#" data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataRemove($item) ?>'><img src="<?= $this->getViewFileUrl('images/closesim_black.png'); ?>" alt=""></i></a>
                        <input name="selectpro" class="p_serchproduct" id="p_serchproductmob<?= $mobilecount;?>" placeholder="Search product" value="<?= /* @escapeNotVerified */ $helper->productAttribute($item, $item->getName(), 'name') ?>">
                        <div class="p_listaddproduct"></div>
                    </div>
                </div>
            </div>
            <div class="p_compaervs"><p>V/S</p></div>
            
            <?php } ?>
            
            <?php for ($i = $mobilecount+1; $i<= $maxMobileItem; $i++) { ?>
            <div class="p_productnameimg">
                <div class="p_compaerproimg">
                        <img src="" alt="">
                </div>
                <div class="p_compierselectinput">
                    <div class="p_productdrop ui-widget">
                        <a href="#" data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataRemove($item) ?>'><img src="<?= $this->getViewFileUrl('images/closesim_black.png'); ?>" alt=""></i></a>
                        <input name="selectpro" class="p_serchproduct" id="p_serchproductmob<?= $i;?>" placeholder="Select a product">
                        <div class="p_listaddproduct"></div>
                    </div>
                </div>
            </div>
            <div class="p_compaervs"><p>V/S</p></div>
            <?php } ?>
        </div>
        <div class="p_compaerpopupbtn">
            <a href="javascript:void(0);">Compare</a>
        </div>
    </div>
    </section>
<div class="a_scrollUpAllever"><i class="fas fa-angle-up"></i></div>
<div class="wishlistTips"></div>
<script type="text/javascript">
    require(['jquery','mage/url','jquery/ui'], function ($,url) {
        $(document).ready(function () {
            var totalItem = <?= $total ?>;
            var mobilemaxItems = <?= $maxMobileItem ?>;
            var availableTags = <?= json_encode($similarProducts); ?>;
            // Hide select for mobile if item count is >=2
            
            if($(window).width()<768){
                // show only first two elements.
                if(totalItem >= mobilemaxItems ) {
                    $(".p_selectbox .p_designbox_select").hide();
                    $(".p_selectbox .p_designbox").slice(2).hide();
                    $(".p_selectproduct .p_disproduct td").css({'width': '50%'});
                    $(".p_selectbox .p_designbox,.p_selectbox .p_designbox_select").css({'width': '50%'});
                    $( "table[name='compare_description'] tr" ).each(function() {
                        $(this).find('td:gt(2)').remove();
                    });
                } else {
                    if(totalItem == 1 ) {
                        $(".p_selectbox .p_designbox_select").first().show();
                        $(".p_selectbox .p_designbox,.p_selectbox .p_designbox_select").css({'width': '50%'});
                        $(".p_selectproduct .p_disproduct td").css({'width': '100%'});
                        $( "table[name='compare_description'] tr" ).each(function() {
                            $(this).find('td:gt(1)').remove();
                        });
                    }
                }
                
            } else {
                //displaynone
            }
            var all = $(".p_serchproduct").map(function() {
                $( "#"+this.id ).autocomplete({
                    minLength: 0,
                    source: availableTags,
                    appendTo: $(this).next(),
                    focus: function( event, ui ) {
                        $( "#"+this.id).attr('data-id',ui.item.value );
                        return false;
                    },
                    select: function( event, ui ) {
                        $( "#"+this.id ).val( ui.item.label);
                        $( "#"+this.id).attr('data-id',ui.item.value );
                        return false;
                    },
                    search: function(event, ui) {},
                });
            });
            
            if($('.a_scrollUpAllever').length > 0){
                $(window).scroll(function(){
                    var getwimS = $(this).scrollTop();
                        if(getwimS > 50){
                            $('.a_scrollUpAllever').addClass('a_scrollUpAlleverShow');
                           }else{
                            $('.a_scrollUpAllever').removeClass('a_scrollUpAlleverShow');
                           }
                });
            }
    
            $('.a_scrollUpAllever').click(function(){
                $('html,body').animate({
                    scrollTop : 0
                },200);
            });
            
            /*** Add Value to session and Redirect to SL Begin***/
            $('.p_nearbystore').click(function(){
                var categoryLob = $(this).data("category-lob");
                findStore(categoryLob);
            });
            /*** Add Value to session and Redirect to SL End***/
        });
        // add to compare - responsive + desktop
        $(document).on('click', '.p_addproductbtn a.addPro, .p_compierheader .p_addproducticon a', function () {
            if($(window).width()<768){
                var mobProBox = $('.p_selectbox .p_designbox').filter(function() {
                    return $(this).css('display') !== 'none';
                }).length;
                if (mobProBox > 1 && mobProBox < 3){
                    $('.p_addproducticon').fadeIn(200);
                } else {
                    $('.p_addproducticon').fadeOut(200);
                }
                $('.p_companerproduct_popup').fadeIn(200);
            } else {
                var product_name = $(this).parent().siblings('.p_productdrop').find("input[name='selectpro']").val();
                if(product_name != '') {
                    var product_id = $(this).parent().siblings('.p_productdrop').find("input[name='selectpro']").attr('data-id');
                    ajaxAdd(product_id);
                }
            }
        });

        // Responsive add to compare
        $('.p_companerproduct_popup .p_compaerpopupbtn a').click(function(){
            $(this).parent().siblings('.p_selectcompaer').find("input[name='selectpro']").each(function() {
                var product_name = $(this).val();
                if(product_name != '') {
                    var product_id = $(this).attr('data-id');
                    ajaxAdd(product_id);
                }
            });
        });

        /**
         * Clear input
         */
        $('.p_companerproduct_popup .p_selectcompaer .p_productnameimg .p_compierselectinput .p_productdrop.ui-widget > a').click(function(){
            $(this).siblings('input').val('');
            $(this).parents('.p_compierselectinput').siblings('.p_compaerproimg').removeClass('active');
        });
        /*
         * Close popup on click on cross
         */
        $('.p_companerproduct_popup .p_compaerproductheader a img').click(function(){
                $('.p_companerproduct_popup').hide();
                if($('.p_selectbox .p_designbox_select').length == 3){
                    $('.p_addproducticon').fadeIn(200);

                }
            });

            /* Hide commaon features*/
            $('#com1,#com2').click(function(){
                if($(this).is(':checked')){
                    $(".samedata").hide("slow");
                }
                else{
                    $(".samedata").show("slow");
                }
            });
        /**
         * Ajax call to add product to compare
         * @param {type} product_id
         * @returns {Boolean}
         */
        function ajaxAdd(product_id)
        {
            if(typeof(product_id) !== "undefined" && product_id !== null) {
                var data = {
                    form_key : $.cookie('form_key'),
                    product  : product_id,
                }
                var url = "<?= $compareHelper->getAjaxAddUrl();?>";
                $.ajax({
                   url: url,
                   type: 'POST',
                   data: data,
                   success: function (resp) {
                       if (resp.success === true) {
                           location.reload();
                       } else {
                           alert(resp.message);
                           return false;
                       }
                   }
               });
            } else {
                return false;
            }
        }
        var prodis;
        if ($('.p_disproduct').length > 0) {
            if ($(window).width() < 768) {
                prodis = $('.p_disproduct').offset().top - 60;
            } else {
                prodis = $('.p_disproduct').offset().top - 200;
            }
        }
        $(window).scroll(function () {
            var scrollwin = $(this).scrollTop();
            if (scrollwin > prodis) {
                $('.p_selectproduct .p_allselect_pro .p_selectanother_product .p_selectbox').addClass('poboFixed');
                $('.p_selectproduct .p_disproduct').css('margin-top', '315px');
            } else {
                $('.p_selectproduct .p_allselect_pro .p_selectanother_product .p_selectbox').removeClass('poboFixed');
                $('.p_selectproduct .p_disproduct').css('margin-top', '0px');
            }
        });
        $('#compare_back').click(function(){
            window.history.back();
        });
        
        function findStore(categoryLob){
            var isLoggedIn;
            var linkUrl = url.build('storelocator');
            var sessionUrl = url.build('storelocator/index/session');
            isLoggedIn = <?php echo $isLoggedIn ? $isLoggedIn : 0; ?>;
            if (categoryLob !== '0' && categoryLob !== '' && typeof categoryLob !== 'undefined') {
                if (isLoggedIn) {
                    $.ajax({
                        url: sessionUrl,
                        type: 'POST',
                        data: {categorylob: categoryLob},
                        dataType: 'json',
                        success: function (data) {
                            window.location.href = linkUrl;
                        }
                    });
                } else {
                    $( ".a_rightnotiPop button" ).trigger( "click" );
                    $(".j_loginPop").addClass("j_showmopopup");
                    $("body").css("overflow", "hidden");
                }
            }
        }
        $(".j_loginPop .backHeader .a_backHeader").click(function(e) {
          $(".j_loginPop").removeClass("j_showmopopup");
          $(".transparentBG").css('display', 'none');
        }); 
        
    });
    
    
</script>


<?php else : ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('You have no items to compare.') ?></div></div>
<?php endif; ?>
