<?php
/*  Copyright (c) BFL (bajaj finserv limited), India  */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$wishlistHelper = $this->helper('Cybage\CustomWishlist\Helper\Data');
$wishlistItems = $wishlistHelper->getWishlistItems();
$block->setItems($wishlistItems);
?>
<div id="layer-product-list">
<div class="products-grid wishlist">
    <?php if (count($block->getItems())): ?>
    <ol class="product-items">
        <?php foreach ($block->getItems() as $item): ?>
            <li data-row="product-item" class="product-item" id="item_<?= $block->escapeHtmlAttr($item->getId()) ?>">
                <?php $productImage = $wishlistHelper->getProductImageUrl($item->getProductId()); 
                    $product = $item->getProduct();
                    $attributeSetId = $product->getAttributeSetId();
                    $categoryLob = $this->helper('Cybage\Storelocator\Helper\Category')->getCategoryLob($attributeSetId);
                    $productName = $product->getName();
                    $productUrl = $product->getProductUrl();
                ?>
                
                    <div class="product-item-info" data-container="product-grid">
                        <div class="p_wishlisthold">
                            <!-- Logic to get Sold Qty dynamically yet to implement-->
                            <p>4,500 Sold</p>
                        </div>
                        <a class="product-item-photo" tabindex="-1" href="<?php echo $productUrl;?>" title="<?php echo $productName;?>">
                            <span class="product-image-container" style="width:240px;">
                            <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                <img class="product-image-photo" src="<?php echo $productImage;?>" max-width="240" max-height="300" alt="<?php echo $productName;?>"></span>
                            </span>
                        </a>
                        <strong class="product-item-name">
                            <a href="<?php echo $productUrl; ?>" title="<?php echo $productName; ?>" class="product-item-link">
                                <?php echo $productName;?>
                            </a>
                        </strong>
                    <div class="p_wishlistEMi">
                        <p>EMI starting at</p>
                        <h2><?= $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($product->getData('emi_starting_at'), true, false); ?></h2>
                    </div>
                    <div class="p_wishlistgetpro">
                        <a href="javascript:void(0)">Get this product</a>
                        <input class="categorylob"type="text" value="<?php echo $categoryLob;?>" hidden="true"/>
                    </div>
                    <div class="product-item-inner">
                    <div class="product-item-actions">
                        <a href="javascript:void(0)" data-role="remove" data-post-remove='<?= /* @noEscape */ $this->helper('Cybage\CustomWishlist\Helper\Data')->getRemoveWishlistParams($item->getId(),0); ?>' title="<?= $block->escapeHtmlAttr(__('Remove Item')) ?>" class="btn-remove action delete">
                            <span><?= $block->escapeHtml(__('Remove item')) ?></span>
                        </a>
                    </div>
                    </div>
                    </div>
                
            </li>
        <?php endforeach; ?>
    </ol>
    <?php else: ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
        </div>
    <?php endif; ?>
</div>
</div>
