<?php
/**
 * BFL Cybage_EdwIntegration
 *
 * @category   Cybage_EdwIntegration Block
 * @package    BFL Cybage_EdwIntegration
 * @copyright  2019 All rights reserved.
 * @license    Proprietary
 * @author     BFL (bajaj finserv limited)
 */

namespace Cybage\EdwIntegration\Block;
 
use Magento\Framework\View\Element\Template;
 
class View extends Template
{
    /**
     * 
     * @param \Magento\Framework\View\Element\Template\Context $context
     * @param array $data
     */
    public function __construct(
        Template\Context $context,
        array $data = []
    ) {
        parent::__construct($context, $data);
    }
 
    /**
     *
     * @return type
     */
    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}
