<?php
/*  Copyright (c) BFL (bajaj finserv limited), India  */
// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>

    <?php
    if ($block->isWishListAllowed()) :
        /** @var \Magento\Wishlist\Helper\Data $wishlistHelper */
        $wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
        $wishlistItem = $wishlistHelper->getWishlistItemCollection()->getItemByColumnValue('product_id', $block->getProduct()->getId());
        $isAddedInWishilistURL = $block->getAddToWishlistParams($block->getProduct());
        $isAddedInWishilist = 'fa fa-heart-o';
        if ($wishlistItem):
            $isAddedInWishilist = "fa fa-heart";
            $isAddedInWishilistURL = $wishlistHelper->getRemoveParams($wishlistItem);
            ?>
        <?php endif; ?>
<li><a class="a_wishPro action towishlist a_addwish" data-href='<?= /* @noEscape */ $isAddedInWishilistURL ?>' data-id='<?= $block->getProduct()->getId() ?>'><i class="<?= $isAddedInWishilist?>"></i></a></li>
    <?php endif; ?>
<script type="text/x-magento-init">
    {
    "body": {
    "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
    }
    }
</script>
