<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<div class="comparepart">
    <div class="wishlistTips">
        <p>Added to Wishlist</p>
    </div>
    <div class="mobilecomparedrop">
        <p>Select products you wish to compare</p>
        <!--EMMS-6 Added below image tag by removing above-->
        <img src='<?php echo $this->getViewFileUrl('images/arrorgup.svg'); ?>' alt="arrorgup">
    </div>
    <div class="compareProduct">
        <a href="JavaScript:Void(0)" class="removeAllFltr">
            <span data-post="<?=
$block->escapeHtml(
        $this->helper('Magento\Catalog\Helper\Product\Compare')->getPostDataClearList()
)
?>"><?= /* @escapeNotVerified */ __('Remove All') ?></span>
        </a>
    </div>
    <button class="compareBTN" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
        <a class="action compare" title="<?= /* @escapeNotVerified */ __('Compare Products') ?>"
           data-bind="attr: {'href': compareProducts().listUrl}">
            COMPARE <span class="counter qty" data-bind="text: compareProducts().count"></span>
        </a>
    </button>
</div>
<script type="text/x-magento-init">
    {"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>}}
</script>


<script type="text/javascript">
    require(["jquery"], function ($) {
        var i = j = 0;
        var maxcount = 3;
        if ($(window).width() < 768) {
            maxcount = 2;
        }
        if (localStorage.getItem('mage-cache-storage')) {
            var collection = JSON.parse(localStorage.getItem('mage-cache-storage'))['compare-products'];
            if (collection) {
                for (var i = 0; i < collection.count; i++) {
                    var compareListProduct = collection.items[i];
                    $('.comparepart .compareProduct').append("<div class='oneboxPro' check-set='" + compareListProduct.id + "'><div class='crossIcon'><i class='fa fa-times' data-post='" + compareListProduct.remove_url + "'></i></div><div class='proImg'><img src='" + compareListProduct.product_image + "' alt=''></div><p>" + compareListProduct.name + "</p></div>");
                }
            }
            for(j=i;j< maxcount; j++){
                //$('.comparepart .compareProduct').append(" <div class='blankCmparBox'><p>Select Another Product</p></div>");
             
            }
        }
    });
    window.compare_remove = "<img src='<?php echo $block->getViewFileUrl('images/compare_blue_2.svg') ?>' /> Compare" ;
    window.compare_added = "<img src='<?php echo $block->getViewFileUrl('images/compare_wht.svg') ?>' /> Added" ;
</script>